# Generated by Django 5.0.6 on 2024-08-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0012_remove_meeting_publication_meeting_event"),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="meetings",
            field=models.ManyToManyField(to="calendarapp.meeting"),
        ),
    ]
