# Generated by Django 5.0.6 on 2024-08-14 23:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0002_publication_meetings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="slug",
        ),
    ]
