# Generated by Django 5.0.6 on 2024-08-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0003_remove_publication_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name="publication",
            name="tags",
        ),
        migrations.AddField(
            model_name="publication",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AddField(
            model_name="publication",
            name="is_private",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name="publication",
            name="liste_tags",
            field=models.ManyToManyField(null=True, to="contents.tags"),
        ),
    ]
