# Generated by Django 5.0.6 on 2024-08-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0004_tags_remove_publication_tags_publication_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
    ]
