# Generated by Django 5.0.6 on 2025-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0005_alter_publication_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="publications",
            field=models.ManyToManyField(
                related_name="spaces", to="contents.publication"
            ),
        ),
    ]
