# Generated by Django 5.0.6 on 2025-09-25 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0006_alter_space_publications"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
    ]
