# Generated by Django 5.0.6 on 2025-09-25 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0007_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="categorie",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contents.category",
            ),
        ),
    ]
