# Generated by Django 5.0.6 on 2025-09-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0017_eventtheme"),
        ("contents", "0008_publication_categorie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="meetings",
            field=models.ManyToManyField(null=True, to="calendarapp.meeting"),
        ),
    ]
