# Generated by Django 5.0.6 on 2025-09-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0017_eventtheme"),
        ("contents", "0009_alter_publication_meetings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="meetings",
            field=models.ManyToManyField(blank=True, to="calendarapp.meeting"),
        ),
    ]
