# Generated by Django 5.0.6 on 2025-10-31 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0010_alter_publication_meetings"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="contents.publication",
            ),
        ),
    ]
