# Generated by Django 5.0.6 on 2026-01-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0018_event_is_test"),
        ("contents", "0011_publication_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publication",
            name="meetings",
        ),
        migrations.AddField(
            model_name="publication",
            name="events",
            field=models.ManyToManyField(blank=True, to="calendarapp.event"),
        ),
    ]
