# Generated by Django 5.0.6 on 2025-07-24 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bucket", "0007_remove_inscription_bucket_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PaiementEntrant",
            fields=[
                (
                    "paiement_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="paiement.paiement",
                    ),
                ),
                ("status", models.IntegerField(default=1, max_length=1)),
                (
                    "tranche",
                    models.IntegerField(
                        default=1, verbose_name=((1, "1"), (2, "2"), (3, "3"))
                    ),
                ),
                ("api_key", models.CharField(default=None, max_length=255)),
                (
                    "parent",
                    models.IntegerField(
                        default=0, verbose_name=((1, "1"), (2, "2"), (3, "3"))
                    ),
                ),
                ("orders", models.ManyToManyField(to="bucket.order")),
            ],
            options={
                "abstract": False,
            },
            bases=("paiement.paiement",),
        ),
    ]
