# Generated by Django 5.0.6 on 2025-07-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paiemententrant",
            name="status",
        ),
        migrations.AddField(
            model_name="paiement",
            name="montant",
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name="paiemententrant",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
