# Generated by Django 5.0.6 on 2025-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0002_remove_paiemententrant_status_paiement_montant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiemententrant",
            name="api_key",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
