# Generated by Django 5.0.6 on 2025-07-31 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0003_alter_paiemententrant_api_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiemententrant",
            name="parent",
            field=models.IntegerField(
                default=0, verbose_name=((1, "1"), (2, "2"), (3, "3"), (4, "4"))
            ),
        ),
        migrations.AlterField(
            model_name="paiemententrant",
            name="tranche",
            field=models.IntegerField(
                default=4, verbose_name=((1, "1"), (2, "2"), (3, "3"), (4, "4"))
            ),
        ),
    ]
