# Generated by Django 5.0.6 on 2025-08-18 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0012_alter_order_total_amount"),
        ("paiement", "0004_alter_paiemententrant_parent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paiemententrant",
            name="api_key",
        ),
        migrations.RemoveField(
            model_name="paiemententrant",
            name="orders",
        ),
        migrations.RemoveField(
            model_name="paiemententrant",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="paiemententrant",
            name="success",
        ),
        migrations.RemoveField(
            model_name="paiemententrant",
            name="tranche",
        ),
        migrations.AddField(
            model_name="paiement",
            name="api_key",
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="parent",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="status",
            field=models.IntegerField(
                default=3, verbose_name=((1, "1"), (2, "2"), (3, "3"))
            ),
        ),
        migrations.AddField(
            model_name="paiement",
            name="tranche",
            field=models.IntegerField(
                default=4, verbose_name=((1, "1"), (2, "2"), (3, "3"), (4, "4"))
            ),
        ),
        migrations.AddField(
            model_name="paiemententrant",
            name="order",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                to="bucket.order",
            ),
            preserve_default=False,
        ),
    ]
