# Generated by Django 5.0.6 on 2025-08-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paiement", "0005_remove_paiemententrant_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="method",
            field=models.IntegerField(
                default=1, verbose_name=((1, "1"), (2, "2"), (3, "3"))
            ),
        ),
    ]
