# Generated by Django 5.0.6 on 2024-06-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0003_alter_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="eventmember",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
