# Generated by Django 5.0.6 on 2024-06-13 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0004_alter_event_id_alter_eventmember_id"),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "m_type",
                    models.IntegerField(
                        default=0,
                        verbose_name=(
                            (0, "Google_Meet"),
                            (1, "Zoom "),
                            (2, "Face-to-face"),
                        ),
                    ),
                ),
                ("events", models.ManyToManyField(to="calendarapp.event")),
                (
                    "publication",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contents.publication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
