# Generated by Django 5.0.6 on 2024-06-14 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0006_alter_meeting_publication"),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="publication",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="contents.publication",
            ),
        ),
    ]
