# Generated by Django 5.0.6 on 2024-06-15 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0007_alter_meeting_publication"),
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="contents.publication"
            ),
        ),
    ]
