# Generated by Django 5.0.6 on 2024-06-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0008_alter_meeting_publication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="events",
        ),
        migrations.CreateModel(
            name="MeetingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event",
                        to="calendarapp.event",
                    ),
                ),
                (
                    "meeting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting",
                        to="calendarapp.meeting",
                    ),
                ),
            ],
            options={
                "unique_together": {("meeting", "event")},
            },
        ),
    ]
