# Generated by Django 5.0.6 on 2024-06-17 23:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0009_remove_meeting_events_meetingevent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MeetingEvent",
            new_name="EventMeeting",
        ),
    ]
