# Generated by Django 5.0.6 on 2024-08-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0010_rename_meetingevent_eventmeeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventmember",
            name="is_added",
            field=models.BooleanField(default=True),
        ),
    ]
