# Generated by Django 5.0.6 on 2024-08-14 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0011_eventmember_is_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meeting",
            name="publication",
        ),
        migrations.AddField(
            model_name="meeting",
            name="event",
            field=models.ForeignKey(
                default=24,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarapp.event",
            ),
            preserve_default=False,
        ),
    ]
