# Generated by Django 5.0.6 on 2024-08-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0012_remove_meeting_publication_meeting_event"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventmeeting",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="eventmeeting",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventmeeting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="eventmeeting",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventmeeting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RemoveField(
            model_name="eventmeeting",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventmeeting",
            name="meeting",
        ),
    ]
