# Generated by Django 5.0.6 on 2024-08-15 01:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0013_alter_eventmeeting_unique_together_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EventMeeting",
        ),
    ]
