# Generated by Django 5.0.6 on 2025-02-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0014_delete_eventmeeting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="m_type",
            field=models.IntegerField(
                default=0,
                verbose_name=((0, "Google_Meet"), (1, "Zoom"), (2, "Face-to-face")),
            ),
        ),
    ]
