# Generated by Django 5.0.6 on 2025-08-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0015_alter_meeting_m_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="link_url",
            field=models.URLField(default=0),
            preserve_default=False,
        ),
    ]
