# Generated by Django 5.0.6 on 2025-08-27 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0016_meeting_link_url"),
        ("lessonapp", "0040_remove_theme_publications"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link_url", models.URLField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarapp.event",
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.theme",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "theme")},
            },
        ),
    ]
