# Generated by Django 5.0.6 on 2025-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0017_eventtheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_test",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
