# Generated by Django 5.0.6 on 2026-01-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0018_event_is_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meeting",
            name="link_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
