# Generated by Django 5.0.6 on 2025-04-01 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("calendarapp", "0015_alter_meeting_m_type"),
        ("lessonapp", "0016_examen_is_chrono"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("color", models.CharField(default="black", max_length=255)),
                ("is_answer", models.BooleanField(default=False)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.document",
                    ),
                ),
                ("document", models.FileField(upload_to="files")),
                ("mime_type", models.CharField(max_length=255)),
                ("hash_value", models.CharField(max_length=255)),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
            bases=("material.document",),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "document_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.document",
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
            bases=("material.document",),
        ),
        migrations.CreateModel(
            name="MaterialEventFile",
            fields=[
                (
                    "material_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.material",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarapp.event",
                    ),
                ),
            ],
            bases=("material.material",),
        ),
        migrations.CreateModel(
            name="MaterialQuestionFile",
            fields=[
                (
                    "material_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.material",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.question",
                    ),
                ),
            ],
            bases=("material.material",),
        ),
        migrations.CreateModel(
            name="MaterialSeanceFile",
            fields=[
                (
                    "material_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.material",
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.seance",
                    ),
                ),
            ],
            bases=("material.material",),
        ),
    ]
