# Generated by Django 5.0.6 on 2025-04-14 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0015_alter_meeting_m_type"),
        ("lessonapp", "0016_examen_is_chrono"),
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MaterialEventFile",
            new_name="MaterialEventDoc",
        ),
        migrations.RenameModel(
            old_name="MaterialSeanceFile",
            new_name="MaterialQuestionDoc",
        ),
        migrations.RenameModel(
            old_name="MaterialQuestionFile",
            new_name="MaterialSeanceDoc",
        ),
        migrations.RemoveField(
            model_name="materialquestiondoc",
            name="seance",
        ),
        migrations.RemoveField(
            model_name="materialseancedoc",
            name="question",
        ),
        migrations.AddField(
            model_name="materialquestiondoc",
            name="question",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessonapp.question",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="materialseancedoc",
            name="seance",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessonapp.seance",
            ),
            preserve_default=False,
        ),
    ]
