# Generated by Django 5.0.6 on 2025-04-17 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0018_remove_question_bloc_number_question_bloc"),
        ("material", "0002_rename_materialeventfile_materialeventdoc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputBox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("color", models.CharField(default="black", max_length=255)),
                ("is_answer", models.BooleanField(default=False)),
                (
                    "input_type",
                    models.IntegerField(
                        default=2, verbose_name=((1, "Checkbox"), (2, "Radio"))
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InputQuestionBox",
            fields=[
                (
                    "inputbox_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.inputbox",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.question",
                    ),
                ),
            ],
            bases=("material.inputbox",),
        ),
    ]
