# Generated by Django 5.0.6 on 2025-04-17 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0003_inputbox_inputquestionbox"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inputbox",
            old_name="name",
            new_name="title",
        ),
    ]
