# Generated by Django 5.0.6 on 2025-04-19 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0022_remove_question_page_question_activity"),
        ("material", "0004_rename_name_inputbox_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialActivityDoc",
            fields=[
                (
                    "material_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.material",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.activity",
                    ),
                ),
            ],
            bases=("material.material",),
        ),
        migrations.DeleteModel(
            name="MaterialSeanceDoc",
        ),
    ]
