# Generated by Django 5.0.6 on 2025-06-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0026_bloc_categorie"),
        ("material", "0005_materialactivitydoc_delete_materialseancedoc"),
    ]

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("color", models.CharField(default="black", max_length=255)),
                ("is_answer", models.BooleanField(default=False)),
                ("paragraph", models.TextField(null=True)),
                ("image", models.ImageField(null=True, upload_to="img")),
                ("number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ActivityComponent",
            fields=[
                (
                    "component_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.component",
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.activity",
                    ),
                ),
            ],
            bases=("material.component",),
        ),
    ]
