# Generated by Django 5.0.6 on 2025-06-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0006_component_activitycomponent"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="img_height",
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name="component",
            name="img_width",
            field=models.IntegerField(default=400),
        ),
    ]
