# Generated by Django 5.0.6 on 2025-06-27 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0008_materialresponseactivitydoc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="material",
            old_name="is_answer",
            new_name="has_answer",
        ),
    ]
