# Generated by Django 5.0.6 on 2025-06-27 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0009_rename_is_answer_material_has_answer"),
    ]

    operations = [
        migrations.AddField(
            model_name="material",
            name="m_type",
            field=models.IntegerField(
                default=1,
                verbose_name=(
                    (1, "COURS"),
                    (2, "Exercice"),
                    (3, "Ma Reponse"),
                    (4, "correction"),
                ),
            ),
        ),
    ]
