# Generated by Django 5.0.6 on 2025-06-30 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0010_material_m_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialresponseactivitydoc",
            name="activity",
        ),
        migrations.AddField(
            model_name="materialresponseactivitydoc",
            name="activity_doc",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="material.materialactivitydoc",
            ),
        ),
    ]
