# Generated by Django 5.0.6 on 2025-07-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0012_checkedresponseinputquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkedresponseinputquestion",
            name="checked",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
