# Generated by Django 5.0.6 on 2025-10-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0014_remove_materialresponseactivitydoc_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="has_answer",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
