# Generated by Django 5.0.6 on 2025-10-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0017_eventtheme"),
        ("material", "0015_alter_material_has_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materialeventdoc",
            name="event",
        ),
        migrations.AddField(
            model_name="materialeventdoc",
            name="events",
            field=models.ManyToManyField(to="calendarapp.event"),
        ),
    ]
