# Generated by Django 5.0.6 on 2025-12-01 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0016_remove_materialeventdoc_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="document",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="material.document",
            ),
        ),
    ]
