# Generated by Django 5.0.6 on 2025-12-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0043_alter_activity_a_type"),
        ("material", "0017_alter_material_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialSeanceDoc",
            fields=[
                (
                    "material_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.material",
                    ),
                ),
                (
                    "seance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.seance",
                    ),
                ),
            ],
            bases=("material.material",),
        ),
    ]
