# Generated by Django 5.0.6 on 2025-12-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0011_publication_parent"),
        ("material", "0018_materialseancedoc"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialPublicationDoc",
            fields=[
                (
                    "material_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.material",
                    ),
                ),
                ("publications", models.ManyToManyField(to="contents.publication")),
            ],
            bases=("material.material",),
        ),
    ]
