# Generated by Django 5.0.6 on 2025-07-09 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0011_remove_materialresponseactivitydoc_activity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResponseInputQuestionBox",
            fields=[
                (
                    "inputbox_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="material.inputbox",
                    ),
                ),
                (
                    "input_question_box",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.inputquestionbox",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=("material.inputbox",),
        ),
    ]
