# Generated by Django 5.0.6 on 2025-07-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0012_responseinputquestionbox"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="responseinputquestionbox",
            name="inputbox_ptr",
        ),
        migrations.AddField(
            model_name="responseinputquestionbox",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=0,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
