# Generated by Django 5.0.6 on 2025-07-09 17:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0013_remove_responseinputquestionbox_inputbox_ptr_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ResponseInputQuestionBox",
            new_name="CheckedResponseInputQuestionBox",
        ),
    ]
