# Generated by Django 5.0.6 on 2025-07-09 17:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0015_checkedresponseinputquestion_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckedResponseInputQuestion",
        ),
    ]
