# Generated by Django 5.0.6 on 2025-03-08 04:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0002_categorie_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categorie",
            name="created_by",
        ),
    ]
