# Generated by Django 5.0.6 on 2025-03-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendarapp", "0015_alter_meeting_m_type"),
        ("lessonapp", "0004_categorie_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="events",
            field=models.ManyToManyField(to="calendarapp.event"),
        ),
    ]
