# Generated by Django 5.0.6 on 2025-03-11 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0005_theme_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=400)),
                (
                    "s_type",
                    models.IntegerField(
                        default=0,
                        verbose_name=((0, "Theorie"), (1, "Pratique"), (2, "Exercice")),
                    ),
                ),
                (
                    "theme",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.theme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Part",
        ),
    ]
