# Generated by Django 5.0.6 on 2025-03-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0009_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="bloc_number",
            field=models.PositiveIntegerField(default=None),
        ),
    ]
