# Generated by Django 5.0.6 on 2025-03-14 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0010_question_bloc_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="events",
        ),
    ]
