# Generated by Django 5.0.6 on 2025-03-31 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0011_remove_theme_events"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="t_type",
        ),
        migrations.AddField(
            model_name="theme",
            name="is_visible",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Examen",
            fields=[
                (
                    "theme_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessonapp.theme",
                    ),
                ),
                ("is_oral", models.BooleanField(default=False)),
                (
                    "t_type",
                    models.IntegerField(
                        default=0, verbose_name=((1, "Controle"), (2, "Examen"))
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("lessonapp.theme",),
        ),
    ]
