# Generated by Django 5.0.6 on 2025-03-31 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0012_remove_theme_t_type_theme_is_visible_examen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examen",
            name="t_type",
            field=models.IntegerField(
                default=1, verbose_name=((1, "Controle"), (2, "Examen"))
            ),
        ),
    ]
