# Generated by Django 5.0.6 on 2025-03-31 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0014_chrono"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Chrono",
        ),
    ]
