# Generated by Django 5.0.6 on 2025-03-31 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0015_delete_chrono"),
    ]

    operations = [
        migrations.AddField(
            model_name="examen",
            name="is_chrono",
            field=models.BooleanField(default=False),
        ),
    ]
