# Generated by Django 5.0.6 on 2025-04-17 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0017_bloc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="bloc_number",
        ),
        migrations.AddField(
            model_name="question",
            name="bloc",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessonapp.bloc",
            ),
        ),
    ]
