# Generated by Django 5.0.6 on 2025-04-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0020_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="t_type",
            field=models.IntegerField(
                default=1, verbose_name=((1, "Quizz"), (2, "Pdf"))
            ),
        ),
    ]
