# Generated by Django 5.0.6 on 2025-04-19 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0021_activity_t_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="page",
        ),
        migrations.AddField(
            model_name="question",
            name="activity",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessonapp.activity",
            ),
        ),
    ]
