# Generated by Django 5.0.6 on 2025-04-21 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0022_remove_question_page_question_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizz",
            name="seance",
        ),
        migrations.DeleteModel(
            name="Page",
        ),
        migrations.DeleteModel(
            name="Quizz",
        ),
    ]
