# Generated by Django 5.0.6 on 2025-04-26 01:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0023_remove_quizz_seance_delete_page_delete_quizz"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="sequences",
        ),
        migrations.AddField(
            model_name="sequence",
            name="session",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessonapp.session",
            ),
        ),
    ]
