# Generated by Django 5.0.6 on 2025-04-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0006_alter_space_publications"),
        ("lessonapp", "0024_remove_session_sequences_sequence_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="publications",
            field=models.ManyToManyField(to="contents.publication"),
        ),
    ]
