# Generated by Django 5.0.6 on 2025-04-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0025_theme_publications"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloc",
            name="categorie",
            field=models.IntegerField(
                default=1, verbose_name=((1, "FOR QUESTION"), (2, "FOR ACTIVITY"))
            ),
        ),
    ]
