# Generated by Django 5.0.6 on 2025-07-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0026_bloc_categorie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name="activity",
            old_name="t_type",
            new_name="a_type",
        ),
        migrations.RemoveField(
            model_name="examen",
            name="t_type",
        ),
        migrations.AddField(
            model_name="examen",
            name="note",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="theme",
            name="t_type",
            field=models.IntegerField(
                default=1, verbose_name=((1, "Cours"), (2, "Examen"))
            ),
        ),
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "activity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lessonapp.activity",
                    ),
                ),
                ("is_oral", models.BooleanField(default=False)),
                ("is_chrono", models.BooleanField(default=False)),
                ("note", models.IntegerField(default=0)),
                (
                    "chrono",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.duration",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("lessonapp.activity",),
        ),
        migrations.AddField(
            model_name="examen",
            name="chrono",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="lessonapp.duration",
            ),
        ),
    ]
