# Generated by Django 5.0.6 on 2025-07-04 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0027_duration_rename_t_type_activity_a_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examen",
            old_name="chrono",
            new_name="duration",
        ),
    ]
