# Generated by Django 5.0.6 on 2025-07-04 11:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0028_rename_chrono_examen_duration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="control",
            old_name="chrono",
            new_name="duration",
        ),
    ]
