# Generated by Django 5.0.6 on 2025-07-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0029_rename_chrono_control_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="activity",
        ),
        migrations.AddField(
            model_name="question",
            name="activities",
            field=models.ManyToManyField(to="lessonapp.activity"),
        ),
    ]
