# Generated by Django 5.0.6 on 2025-07-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0030_remove_question_activity_question_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
