# Generated by Django 5.0.6 on 2025-07-07 00:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0031_question_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="activities",
        ),
        migrations.RemoveField(
            model_name="question",
            name="number",
        ),
        migrations.RemoveField(
            model_name="question",
            name="points",
        ),
    ]
