# Generated by Django 5.0.6 on 2025-07-07 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "lessonapp",
            "0032_remove_question_activities_remove_question_number_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Activityquestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("points", models.PositiveIntegerField()),
                ("number", models.IntegerField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.activity",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lessonapp.question",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
