# Generated by Django 5.0.6 on 2025-07-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0033_activityquestion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityquestion",
            name="points",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
