# Generated by Django 5.0.6 on 2025-07-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0034_alter_activityquestion_points"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="description",
            field=models.TextField(default=None),
        ),
    ]
