# Generated by Django 5.0.6 on 2025-07-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0036_activitystate"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
    ]
