# Generated by Django 5.0.6 on 2025-07-11 14:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0037_theme_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="image",
        ),
    ]
