# Generated by Django 5.0.6 on 2025-07-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0038_remove_theme_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="theme",
            name="image",
            field=models.ImageField(null=True, upload_to="img"),
        ),
    ]
