# Generated by Django 5.0.6 on 2025-08-27 21:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0039_theme_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="theme",
            name="publications",
        ),
    ]
