# Generated by Django 5.0.6 on 2025-09-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0040_remove_theme_publications"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="state",
            field=models.IntegerField(
                default=1, verbose_name=((1, "Init"), (2, "Open"), (3, "Closed"))
            ),
        ),
    ]
