# Generated by Django 5.0.6 on 2025-09-11 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0041_activity_state"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Activitystate",
        ),
    ]
