# Generated by Django 5.0.6 on 2025-11-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessonapp", "0042_delete_activitystate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="a_type",
            field=models.IntegerField(
                default=1, verbose_name=((1, "Quizz"), (2, "Pdf"), (3, "Link"))
            ),
        ),
    ]
