# Generated by Django 5.0.6 on 2024-08-27 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0001_initial"),
        ("contents", "0003_remove_publication_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bucket",
            name="publications",
        ),
        migrations.AddField(
            model_name="bucket",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bucket",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="bucket",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="bucket",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="BucketOfContents",
            fields=[
                (
                    "bucket_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="bucket.bucket",
                    ),
                ),
                ("publications", models.ManyToManyField(to="contents.publication")),
            ],
            options={
                "abstract": False,
            },
            bases=("bucket.bucket",),
        ),
    ]
