# Generated by Django 5.0.6 on 2024-09-22 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0003_bucketofinscriptions_inscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="bucketofinscriptions",
            name="status",
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name="inscription",
            name="status",
            field=models.IntegerField(default=1, max_length=1),
        ),
    ]
