# Generated by Django 5.0.6 on 2025-04-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0004_bucketofinscriptions_status_alter_inscription_status"),
        ("contents", "0005_alter_publication_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscription",
            name="publication",
        ),
        migrations.AddField(
            model_name="inscription",
            name="publications",
            field=models.ManyToManyField(to="contents.publication"),
        ),
    ]
