# Generated by Django 5.0.6 on 2025-07-18 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0006_alter_inscription_participant"),
        ("calendarapp", "0015_alter_meeting_m_type"),
        ("contents", "0006_alter_space_publications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscription",
            name="bucket",
        ),
        migrations.RemoveField(
            model_name="inscription",
            name="publications",
        ),
        migrations.AddField(
            model_name="inscription",
            name="change_calender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="inscription",
            name="events",
            field=models.ManyToManyField(to="calendarapp.event"),
        ),
        migrations.AddField(
            model_name="inscription",
            name="publication",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="contents.publication",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.IntegerField(
                        default=1,
                        verbose_name=((1, "Open"), (2, "Pending"), (3, "Closed")),
                    ),
                ),
                (
                    "bucket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bucket.bucketofinscriptions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="inscription",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="bucket.order",
            ),
        ),
    ]
