# Generated by Django 5.0.6 on 2025-07-25 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0007_remove_inscription_bucket_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inscription",
            name="events",
        ),
    ]
