# Generated by Django 5.0.6 on 2025-08-16 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0008_remove_inscription_events"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bucketofinscriptions",
            name="status",
        ),
        migrations.RemoveField(
            model_name="inscription",
            name="change_calender",
        ),
        migrations.RemoveField(
            model_name="inscription",
            name="order",
        ),
        migrations.RemoveField(
            model_name="order",
            name="bucket",
        ),
        migrations.AddField(
            model_name="bucketofinscriptions",
            name="inscriptions",
            field=models.ManyToManyField(to="bucket.inscription"),
        ),
        migrations.AddField(
            model_name="order",
            name="buyer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=10, default=8, max_digits=19),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="inscription",
            name="status",
            field=models.IntegerField(
                default=1,
                verbose_name=((1, "Waiting"), (2, "Confirmed"), (3, "Cancel")),
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                default=1,
                verbose_name=(
                    (1, "Pending"),
                    (2, "Total_Paid"),
                    (3, "Semi_Paid"),
                    (4, "Failed"),
                ),
            ),
        ),
        migrations.CreateModel(
            name="OrderInscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bucket.inscription",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="bucket.order"
                    ),
                ),
            ],
        ),
    ]
