# Generated by Django 5.0.6 on 2025-08-17 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0009_remove_bucketofinscriptions_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="inscription",
            field=models.ForeignKey(
                default=7,
                on_delete=django.db.models.deletion.CASCADE,
                to="bucket.inscription",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                default=1,
                verbose_name=(
                    (1, "Pending"),
                    (2, "Total_Paid"),
                    (3, "Partially_Paid"),
                    (4, "Failed"),
                ),
            ),
        ),
    ]
