# Generated by Django 5.0.6 on 2025-08-17 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0010_order_inscription_alter_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="inscription",
        ),
    ]
