# Generated by Django 5.0.6 on 2025-08-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0011_remove_order_inscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default="00000.00", max_digits=8
            ),
        ),
    ]
