# Generated by Django 5.0.6 on 2025-10-29 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0012_alter_order_total_amount"),
        ("calendarapp", "0018_event_is_test"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_parent",
                    models.EmailField(
                        blank=True,
                        help_text="Adresse email du parent.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "telephone_parent",
                    models.CharField(
                        blank=True,
                        help_text="Numéro de téléphone du parent.",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("is_reserved", models.BooleanField(default=False)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="calendarapp.event",
                    ),
                ),
                (
                    "inscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bucket.inscription",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "inscription")},
            },
        ),
    ]
