# Generated by Django 5.0.6 on 2025-10-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0013_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inscription",
            name="status",
            field=models.IntegerField(
                default=1,
                verbose_name=(
                    (0, "Testing"),
                    (1, "Waiting"),
                    (2, "Confirmed"),
                    (3, "Cancel"),
                ),
            ),
        ),
    ]
