# Generated by Django 5.0.6 on 2025-10-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0015_reservation_created_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="is_reserved",
        ),
        migrations.AlterField(
            model_name="inscription",
            name="status",
            field=models.IntegerField(
                default=0,
                verbose_name=(
                    (0, "Testing"),
                    (1, "Waiting"),
                    (2, "Confirmed"),
                    (3, "Cancel"),
                ),
            ),
        ),
    ]
