# Generated by Django 5.0.6 on 2025-10-31 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0016_remove_reservation_is_reserved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="list_attente",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
