# Generated by Django 5.0.6 on 2025-10-31 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bucket", "0017_reservation_list_attente"),
        ("calendarapp", "0018_event_is_test"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="event",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="calendarapp.event",
            ),
        ),
    ]
